version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  kafka:
    image: spotify/kafka
    container_name: "kafka"
    ports:
      - 2181:2181
      - 9092:9092
  app:
    image: gabrielsouzaa/api-ordem-manutencao
    ports:
      - 10001:10001
    links:
      - mongodb
      - kafka
