version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: reciclatown/api-ordem-manutencao
    ports:
      - 10001:10001
    links:
      - mongodb